### PR TITLE
Sqlmodel support

### PR DESCRIPTION
**Pull request by cfhowes**
#57 
a couple of updates:

 - add support for SQLModel output 
 - Ensure that `snake_case` is used for index/unique/constaints in the output.

### CODE REVIEW

**Comment by fitmeal-miyoshi** [comment]
@xnuinside (@cfhowes )
Thank you for your support with SQLModel. SQLModel support is not available with `pip install omymodels`, but how can it be made to support SQLModel?

I look forward to your kind assistance.

**Comment by cfhowes** [comment]
@fitmeal-miyoshi if you clone the repo on the `main` branch you will have the support for SQLModel.  You will need to make sure that the cloned repo is what is on your path (rather then the one installed via pip).

**Comment by xnuinside** [comment]
@fitmeal-miyoshi @cfhowes I will release version with it today, I thought to add more features before release, but my plans was broken by the reality ( didn't have time on it

**Comment by xnuinside** [comment]
released in 0.16.0

**Pull request merged**
