### PR TITLE
added bytes type for Pydantic

### PR DESCRIPTION
**Pull request by vortex14**
Added support for the byte type for the Pydantic model

```

class User(BaseModel):
    avatar: bytes
```

### CODE REVIEW

**Comment by xnuinside** [comment]
@vortex14 hi, thanks for opening your PR! Can you add small test to be sure, that this mapping do exactly that expected?

**Comment by vortex14** [comment]
> @vortex14 hi, thanks for opening your PR! Can you add small test to be sure, that this mapping do exactly that expected?

it's ready

**Comment by xnuinside** [comment]
@vortex14 pipeline is failed :) small flake8 issue - https://github.com/xnuinside/omymodels/runs/6111686198?check_suite_focus=true

**Comment by xnuinside** [comment]
@vortex14 not sure what is with pipeline) I will merge PR and fix this pipeline issue later. Thank you for the PR!

**Comment by xnuinside** [comment]
@vortex14  released in 0.11.1 version

**Pull request merged**
